# @package _global_

agent:
  config:
    # Setup actors structure
    model:
      config:
        actors:
          - _target_: protomotions.agents.ppo.model.PPOActor
            _recursive_: False
            num_out: 24
            config:
              name: lower
              actor_logstd: -2.9
              mu_model:
                _target_: protomotions.agents.common.mlp.MultiHeadedMLP
                _recursive_: False
                config:
                  num_out: ${....num_out}
                  input_models:
                    self_obs:
                      _target_: protomotions.agents.common.common.Flatten
                      _recursive_: False
                      num_in: ${robot.self_obs_size}
                      num_out: ${.num_in}
                      config:
                        obs_key: self_obs
                        normalize_obs: True
                        norm_clamp_value: 5
                  trunk:
                    _target_: protomotions.agents.common.mlp.MLP
                    _recursive_: False
                    num_out: ${..num_out}
                    config:
                      layers:
                        - units: 1024
                          activation: tanh
                          use_layer_norm: false
                        - units: 512
                          activation: tanh
                          use_layer_norm: false
          - _target_: protomotions.agents.ppo.model.PPOActor
            _recursive_: False
            num_out: 33
            config:
              name: upper
              actor_logstd: -2.9
              mu_model:
                _target_: protomotions.agents.common.mlp.MultiHeadedMLP
                _recursive_: False
                config:
                  num_out: ${....num_out}
                  input_models:
                    self_obs:
                      _target_: protomotions.agents.common.common.Flatten
                      _recursive_: False
                      num_in: ${robot.self_obs_size}
                      num_out: ${.num_in}
                      config:
                        obs_key: self_obs
                        normalize_obs: True
                        norm_clamp_value: 5
                  trunk:
                    _target_: protomotions.agents.common.mlp.MLP
                    _recursive_: False
                    num_out: ${..num_out}
                    config:
                      layers:
                        - units: 1024
                          activation: tanh
                          use_layer_norm: false
                        - units: 512
                          activation: tanh
                          use_layer_norm: false
          - _target_: protomotions.agents.ppo.model.PPOActor
            _recursive_: False
            num_out: 48
            config:
              name: left_hand
              actor_logstd: -2.9
              mu_model:
                _target_: protomotions.agents.common.mlp.MultiHeadedMLP
                _recursive_: False
                config:
                  num_out: ${....num_out}
                  input_models:
                    self_obs:
                      _target_: protomotions.agents.common.common.Flatten
                      _recursive_: False
                      num_in: ${robot.self_obs_size}
                      num_out: ${.num_in}
                      config:
                        obs_key: self_obs
                        normalize_obs: True
                        norm_clamp_value: 5
                  trunk:
                    _target_: protomotions.agents.common.mlp.MLP
                    _recursive_: False
                    num_out: ${..num_out}
                    config:
                      layers:
                        - units: 1024
                          activation: tanh
                          use_layer_norm: false
                        - units: 512
                          activation: tanh
                          use_layer_norm: false
          - _target_: protomotions.agents.ppo.model.PPOActor
            _recursive_: False
            num_out: 48
            config:
              name: right_hand
              actor_logstd: -2.9
              mu_model:
                _target_: protomotions.agents.common.mlp.MultiHeadedMLP
                _recursive_: False
                config:
                  num_out: ${....num_out}
                  input_models:
                    self_obs:
                      _target_: protomotions.agents.common.common.Flatten
                      _recursive_: False
                      num_in: ${robot.self_obs_size}
                      num_out: ${.num_in}
                      config:
                        obs_key: self_obs
                        normalize_obs: True
                        norm_clamp_value: 5
                  trunk:
                    _target_: protomotions.agents.common.mlp.MLP
                    _recursive_: False
                    num_out: ${..num_out}
                    config:
                      layers:
                        - units: 1024
                          activation: tanh
                          use_layer_norm: false
                        - units: 512
                          activation: tanh
                          use_layer_norm: false

        actor_optimizer:
          _target_: torch.optim.Adam
          lr: 2e-5
